### ISSUE TITLE
All Servers

### ISSUE THREAD

**Issue by Anzulia** [Noer09/AimPlace-Issues#13]
Følgende er ønsker:

* Server Hop.
https://forums.alliedmods.net/showthread.php?t=113807

!spec, !afk player.
*  !spec (player name), !afk (player name).

**Comment by Noer09** [comment]
Serverhop er kørende igen samt alle skulle servere skulle have !afk og !mspec, for at flytte en spiller.
!afk kan ikke benyttes mod spillere, men skal benyttes af spilleren selv.
