### ISSUE TITLE
Advertisements rettelser

### ISSUE THREAD

**Issue by Anzulia** [Noer09/AimPlace-Issues#5]
Vi skal have rettet disse ting til:

Advertisement: 

● Ved Join:
- Velkommen til, [DK] AimPlace.dk - Retakes #1 [!WS|!KNIFE|!GLOVES|GAMEME], (Player)!

● Ved !Discord skal vores Discord sendes direkte ud i chatten.
Værsegod. Her er vores Discord som ønsket. Tag del i fællesskabet og join med det samme. (Link her).

● [AimPlace] skal rettes til [AimPlace.dk]

●Tilføj serveren til din favorit: IP HER
- "IP HER" skal rettes til X server.

**Comment by Noer09** [comment]
Der er nu tilføjet en join besked.
!discord sender nu en chat besked med discord link
[AimPlace] præfiks er nu ændret til [AimPlace.dk] præfiks.
Reklamerne er nu tilpasset for server adresserne.
