### ISSUE TITLE
GameME

### ISSUE THREAD

**Issue by Anzulia** [Noer09/AimPlace-Issues#7]
Vi skal have GameME sat ned, så det automatisk er aktiveret ved 2 eller 4 spillere.
Vi skal have et !top score ligesom med rankme (hvis muligt.)

Vi skal have tilføjet GameME på hjemmesiden så det er nemt at finde derind, og se stats fra x server.

**Comment by Noer09** [comment]
GameMe er sat ned til 2 aktive (humane) spillere.
Der kan nu benyttes !top.

GameMe kan indsættes på hjemmesiden via Menu funktionen i adminpanelet.
URL til GameMe: https://gameme.aimplace.dk/
